spring:
  application:
    name: oms
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  jpa:
    hibernate:
      ddl-auto: validate
  security:
    # should be passed with env variables
    user:
      name: ""
      password: ""
      roles: [ ]

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true
      show-details: when_authorized