spring:
  application:
    name: oms
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  jpa:
    hibernate:
      ddl-auto: validate

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true
      show-details: when_authorized

application:
  # should be passed with env variables
  security:
    admin-user: ""
    admin-password: ""
    jwt-secret: ""
    jwt-ttl-seconds: 3600