spring:
  profiles:
    active: local
  application:
    name: oms
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  jpa:
    hibernate:
      ddl-auto: validate

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true
      show-details: when_authorized

application:
  order-service:
    optimistic-lock-max-retries: 3
  security:
    # Values must be provided via environment variables or externalized config in prod
    admin-user: "${APP_ADMIN_USER:}"
    admin-password: "${APP_ADMIN_PASSWORD:}"
    jwt-secret: "${APP_JWT_SECRET:}"
    jwt-ttl-seconds: ${APP_JWT_TTL_SECONDS:3600}