spring:
  profiles:
    active: prod
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

server:
  port: 8080
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 1024

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true
      show-details: when_authorized

logging:
  level:
    root: INFO

application:
  security:
    # Values must be provided via environment variables or externalized config in prod
    admin-user: "${APP_ADMIN_USER:}"
    admin-password: "${APP_ADMIN_PASSWORD:}"
    jwt-secret: "${APP_JWT_SECRET:}"
    jwt-ttl-seconds: ${APP_JWT_TTL_SECONDS:3600}
